apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: nvidia-operator
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "20"
    helm.sh/hook-delete-policy: before-hook-creation
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      nvidiaOperator: enabled
  repoURL: https://helm.ngc.nvidia.com/nvidia
  chartName: gpu-operator
  options:
    waitForJobs: false
    wait: false
    timeout: 5m
    install:
      createNamespace: true
