apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: volcano-sh
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "20"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  clusterSelector:
    matchLabels:
      volcano: enabled
  repoURL: https://volcano-sh.github.io/helm-charts
  chartName: volcano
  options:
    waitForJobs: false
    wait: false
    timeout: 5m
    install:
      createNamespace: true
