apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: test-workspace-template
  namespace: default
  labels:
    app: test-workspace
    template: workspace
spec:
  helm:
    chartSource:
      remoteSourceSpec:
        git:
          url: https://github.com/exalsius/exalsius-workspace-templates.git
          ref:
            branch: main
          interval: 10m
      path: "./workspace-templates/test-workspace"
