apiVersion: v2
name: exalsius
description: A Helm umbrella chart to deploy the exalsius operator along with its dependencies.
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: exalsius-operator
    version: 0.1.0
    repository: file://charts/operator
    condition: operator.enabled

  - name: skypilot-nightly
    version: "1.0.0-dev.20250318"
    repository: https://helm.skypilot.co
    condition: skypilot-nightly.enabled

  - name: gpu-operator
    version: "v24.9.2"
    repository: https://helm.ngc.nvidia.com/nvidia
    condition: nvidia-operator.enabled
