apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exalsius-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "exalsius-operator.name" . }}