# This rule is not used by the project exalsius-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the training.exalsius.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: exalsius-operator
    app.kubernetes.io/managed-by: kustomize
  name: dilocopytorchtraining-editor-role
rules:
- apiGroups:
  - training.exalsius.ai
  resources:
  - dilocopytorchtrainings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.exalsius.ai
  resources:
  - dilocopytorchtrainings/status
  verbs:
  - get
