# This rule is not used by the project exalsius-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infra.exalsius.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: exalsius-operator
    app.kubernetes.io/managed-by: kustomize
  name: infra-user-admin-role
rules:
- apiGroups:
  - infra.exalsius.ai
  resources:
  - users
  verbs:
  - '*'
- apiGroups:
  - infra.exalsius.ai
  resources:
  - users/status
  verbs:
  - get
