---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - get
  - list
- apiGroups:
  - infra.exalsius.ai
  resources:
  - colonies
  verbs:
  - get
  - list
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - remotemachines
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - remotemachines/status
  verbs:
  - get
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments
  - servicetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments/status
  verbs:
  - get
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - servicesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspaces.exalsius.ai
  resources:
  - workspaceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workspaces.exalsius.ai
  resources:
  - workspaceclasses/status
  - workspacedeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workspaces.exalsius.ai
  resources:
  - workspacedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspaces.exalsius.ai
  resources:
  - workspacedeployments/finalizers
  verbs:
  - update
