# This rule is not used by the project exalsius-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to training.exalsius.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: exalsius-operator
    app.kubernetes.io/managed-by: kustomize
  name: training-ddpjob-viewer-role
rules:
- apiGroups:
  - training.exalsius.ai
  resources:
  - ddpjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - training.exalsius.ai
  resources:
  - ddpjobs/status
  verbs:
  - get
