apiVersion: v1
kind: Secret
metadata:
  name: ${credential_name}-cluster-identity-secret
  namespace: ${namespace}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  AccessKeyID: ${ACCESS_KEY_ID}
  SecretAccessKey: ${SECRET_ACCESS_KEY}