apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: ${credential_name}-credential
  namespace: ${namespace}
spec:
  description: "${description}"
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSClusterStaticIdentity
    name: ${credential_name}-cluster-identity
