apiVersion: v1
kind: Secret
metadata:
  name: docker-regional-cluster-secret
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-child-cluster-secret
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
