apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: docker-regional-cluster-stub-credential
  namespace: kcm-system
spec:
  description: Docker Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: docker-regional-cluster-secret
    namespace: kcm-system
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: docker-child-cluster-stub-credential
  namespace: kcm-system
spec:
  description: Docker Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: docker-child-cluster-secret
    namespace: kcm-system
