apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: docker-stub-credential
  namespace: kcm-system
spec:
  description: Docker Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: docker-cluster-secret
    namespace: kcm-system
