kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0 # Specify the Kubernetes version
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
    extraPortMappings:
      - containerPort: 30050
        hostPort: 30050
        protocol: TCP
      - containerPort: 30051
        hostPort: 30051
        protocol: TCP
      - containerPort: 30333
        hostPort: 30333
        protocol: TCP
      - containerPort: 30334
        hostPort: 30334
        protocol: TCP
