apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: ${credential_name}-credential
  namespace: ${namespace}
spec:
  description: "${description}"
  identityRef:
    apiVersion: v1
    kind: Secret
    name: ${credential_name}-cluster-identity-secret
    namespace: ${namespace}