apiVersion: v1
kind: ConfigMap
metadata:
  name: ${credential_name}-resource-template
  namespace: ${namespace}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
data:
  configmap.yaml: |
    {{- $secret := (getResource "InfrastructureProviderIdentity") -}}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: ${credential_name}-cluster-identity-secret
      namespace: ${namespace}
    type: Opaque
    data:
      cloud-sa.json: {{ index $secret "data" "credentials" }}