apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.aws.awsCredentials.accessKeyId | b64enc | quote }}
  aws_secret_access_key: {{ .Values.aws.awsCredentials.secretAccessKey | b64enc | quote }}
