{{- if .Values.docker.enabled }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
 name: docker
 namespace: {{ .Release.Namespace }}
spec:
 version: {{ .Values.capi.docker_provider_version }}
{{- end }}