apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: AddonProvider
metadata:
 name: helm
 namespace: {{ .Release.Namespace }}
# annotations:
#   helm.sh/hook: post-install,post-upgrade
#   helm.sh/hook-weight: "20"
spec:
 version: {{ .Values.capi.helm_addon_provider_version }}
