---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
 name: k0sproject-k0smotron
 namespace: {{ .Release.Namespace }}
 #annotations:
 #  helm.sh/hook: post-install,post-upgrade
 #  helm.sh/hook-weight: "10"
spec:
 version: {{ .Values.capi.k0smotron_control_plane_provider_version }}
 deployment:
    containers:
    - name: manager
      resources:
        limits:
          memory: 512Mi
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
 name: k0sproject-k0smotron
 namespace: {{ .Release.Namespace }}
 #annotations:
 #  helm.sh/hook: post-install,post-upgrade
 #  helm.sh/hook-weight: "10"
spec:
 version: {{ .Values.capi.k0smotron_bootstrap_provider_version }}

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
 name: k0sproject-k0smotron
 namespace: {{ .Release.Namespace }}
 #annotations:
 #  helm.sh/hook: post-install,post-upgrade
 #  helm.sh/hook-weight: "10"
spec:
 version: {{ .Values.capi.k0smotron_infrastructure_provider_version }}