---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-webhook-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wait-for-webhook-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wait-for-webhook-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: wait-for-webhook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: wait-for-webhook-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-capi-webhook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: wait-for-webhook-sa
      restartPolicy: Never
      containers:
      - name: wait-for-webhook
        image: curlimages/curl
        command:
          - sh
          - -c
          - |
            until curl -k -sf https://capi-operator-webhook-service.{{ .Release.Namespace }}.svc:443/validate-operator-cluster-x-k8s-io-v1alpha2-coreprovider; do
                echo "Webhook not ready, retrying in 5 seconds..."
                sleep 5
            done
            echo "Webhook is ready!"