apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-capi-core-deployment
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: wait-for-webhook-sa
      containers:
        - name: wait
          image: bitnami/kubectl
          command:
            - "/bin/sh"
            - "-c"
            - |
              until kubectl rollout status deployment capi-controller-manager -n {{ .Release.Namespace }} --timeout=5m; do
                echo "Waiting for capi-controller-manager to be ready..."
                sleep 10
              done
              echo "capi-controller-manager Deployment is ready!"