apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "operator.name" . }}
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
