apiVersion: infra.exalsius.ai/v1
kind: Colony
metadata:
  name: aws-colony
  namespace: default
spec:
  colonyClusters:
    - clusterName: aws-1
      clusterDeploymentSpec:
        template: aws-standalone-cp-1-0-0
        credential: aws-credential
        config:
          clusterLabels: {}
          region: eu-central-1
          controlPlaneNumber: 1
          controlPlane:
            instanceType: t3.small
          workersNumber: 1
          worker:
            instanceType: t3.small
