apiVersion: infra.exalsius.ai/v1
kind: Colony
metadata:
  name: docker-colony
  namespace: default
spec:
  colonyClusters:
    - clusterName: docker-1
      clusterDeploymentSpec:
          template: docker-hosted-cp-1-0-0
          credential: docker-stub-credential
          config:
            clusterLabels: {}
            workersNumber: 2

