apiVersion: infra.exalsius.ai/v1
kind: Colony
metadata:
  name: k0rdent-docker-colony
  namespace: kcm-system
spec:
  colonyClusters:
    - clusterName: docker-1
      clusterDeploymentSpec:
          template: docker-hosted-cp-1-0-0
          credential: docker-stub-credential
          config:
            clusterLabels: {}
            workersNumber: 2
    - clusterName: aws-1
      clusterDeploymentSpec:
          template: aws-standalone-cp-1-0-0
          credential: aws-cluster-identity-cred
          config:
            clusterLabels: {}
            region: eu-central-1
            controlPlane:
              instanceType: t3.small
            worker:
              instanceType: t3.small


