apiVersion: infra.exalsius.ai/v1
kind: Colony
metadata:
  name: remote-colony
spec:
  k8sVersion: v1.27.2
  workloadDependencies:
    - name: volcano-sh

  hostedControlPlaneEnabled: true 

  colonyClusters:
    - clusterName: remote-1
      remoteClusterEnabled: true
