//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEndpoint) DeepCopyInto(out *AccessEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEndpoint.
func (in *AccessEndpoint) DeepCopy() *AccessEndpoint {
	if in == nil {
		return nil
	}
	out := new(AccessEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntry) DeepCopyInto(out *AccessEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntry.
func (in *AccessEntry) DeepCopy() *AccessEntry {
	if in == nil {
		return nil
	}
	out := new(AccessEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentRef) DeepCopyInto(out *ClusterDeploymentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentRef.
func (in *ClusterDeploymentRef) DeepCopy() *ClusterDeploymentRef {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSummary) DeepCopyInto(out *EventSummary) {
	*out = *in
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSummary.
func (in *EventSummary) DeepCopy() *EventSummary {
	if in == nil {
		return nil
	}
	out := new(EventSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureContext) DeepCopyInto(out *FailureContext) {
	*out = *in
	if in.ServiceSetStatus != nil {
		in, out := &in.ServiceSetStatus, &out.ServiceSetStatus
		*out = new(ServiceSetStatusSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.RecentEvents != nil {
		in, out := &in.RecentEvents, &out.RecentEvents
		*out = make([]EventSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureContext.
func (in *FailureContext) DeepCopy() *FailureContext {
	if in == nil {
		return nil
	}
	out := new(FailureContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeasibilityStatus) DeepCopyInto(out *FeasibilityStatus) {
	*out = *in
	in.EvaluatedAt.DeepCopyInto(&out.EvaluatedAt)
	in.Demanded.DeepCopyInto(&out.Demanded)
	in.Available.DeepCopyInto(&out.Available)
	if in.Missing != nil {
		in, out := &in.Missing, &out.Missing
		*out = new(ResourceTotals)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeasibilityStatus.
func (in *FeasibilityStatus) DeepCopy() *FeasibilityStatus {
	if in == nil {
		return nil
	}
	out := new(FeasibilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrerequisiteSpec) DeepCopyInto(out *PrerequisiteSpec) {
	*out = *in
	out.ServiceTemplate = in.ServiceTemplate
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrerequisiteSpec.
func (in *PrerequisiteSpec) DeepCopy() *PrerequisiteSpec {
	if in == nil {
		return nil
	}
	out := new(PrerequisiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrerequisiteStatus) DeepCopyInto(out *PrerequisiteStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrerequisiteStatus.
func (in *PrerequisiteStatus) DeepCopy() *PrerequisiteStatus {
	if in == nil {
		return nil
	}
	out := new(PrerequisiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInjectionMap) DeepCopyInto(out *ResourceInjectionMap) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
	if in.GPUCount != nil {
		in, out := &in.GPUCount, &out.GPUCount
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
	if in.GPUVendor != nil {
		in, out := &in.GPUVendor, &out.GPUVendor
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
	if in.GPUType != nil {
		in, out := &in.GPUType, &out.GPUType
		*out = make([]InjectionPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInjectionMap.
func (in *ResourceInjectionMap) DeepCopy() *ResourceInjectionMap {
	if in == nil {
		return nil
	}
	out := new(ResourceInjectionMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.GPUCount != nil {
		in, out := &in.GPUCount, &out.GPUCount
		*out = new(int32)
		**out = **in
	}
	if in.GPUVendor != nil {
		in, out := &in.GPUVendor, &out.GPUVendor
		*out = new(GPUVendor)
		**out = **in
	}
	if in.GPUType != nil {
		in, out := &in.GPUType, &out.GPUType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTotals) DeepCopyInto(out *ResourceTotals) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.GPUCount != nil {
		in, out := &in.GPUCount, &out.GPUCount
		*out = new(int32)
		**out = **in
	}
	if in.GPUVendor != nil {
		in, out := &in.GPUVendor, &out.GPUVendor
		*out = new(GPUVendor)
		**out = **in
	}
	if in.GPUType != nil {
		in, out := &in.GPUType, &out.GPUType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTotals.
func (in *ResourceTotals) DeepCopy() *ResourceTotals {
	if in == nil {
		return nil
	}
	out := new(ResourceTotals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSetStatusSummary) DeepCopyInto(out *ServiceSetStatusSummary) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceStateSummary, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSetStatusSummary.
func (in *ServiceSetStatusSummary) DeepCopy() *ServiceSetStatusSummary {
	if in == nil {
		return nil
	}
	out := new(ServiceSetStatusSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStateSummary) DeepCopyInto(out *ServiceStateSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStateSummary.
func (in *ServiceStateSummary) DeepCopy() *ServiceStateSummary {
	if in == nil {
		return nil
	}
	out := new(ServiceStateSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTemplateRef) DeepCopyInto(out *ServiceTemplateRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTemplateRef.
func (in *ServiceTemplateRef) DeepCopy() *ServiceTemplateRef {
	if in == nil {
		return nil
	}
	out := new(ServiceTemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserFacingConfigField) DeepCopyInto(out *UserFacingConfigField) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserFacingConfigField.
func (in *UserFacingConfigField) DeepCopy() *UserFacingConfigField {
	if in == nil {
		return nil
	}
	out := new(UserFacingConfigField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceClass) DeepCopyInto(out *WorkspaceClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceClass.
func (in *WorkspaceClass) DeepCopy() *WorkspaceClass {
	if in == nil {
		return nil
	}
	out := new(WorkspaceClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceClassList) DeepCopyInto(out *WorkspaceClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkspaceClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceClassList.
func (in *WorkspaceClassList) DeepCopy() *WorkspaceClassList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceClassSpec) DeepCopyInto(out *WorkspaceClassSpec) {
	*out = *in
	out.ServiceTemplate = in.ServiceTemplate
	in.DefaultResources.DeepCopyInto(&out.DefaultResources)
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]PrerequisiteSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AccessEndpoints != nil {
		in, out := &in.AccessEndpoints, &out.AccessEndpoints
		*out = make([]AccessEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.UserFacingConfig != nil {
		in, out := &in.UserFacingConfig, &out.UserFacingConfig
		*out = make([]UserFacingConfigField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployTimeout != nil {
		in, out := &in.DeployTimeout, &out.DeployTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PrerequisiteDeployTimeout != nil {
		in, out := &in.PrerequisiteDeployTimeout, &out.PrerequisiteDeployTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DefaultValues != nil {
		in, out := &in.DefaultValues, &out.DefaultValues
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceInjection != nil {
		in, out := &in.ResourceInjection, &out.ResourceInjection
		*out = new(ResourceInjectionMap)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceClassSpec.
func (in *WorkspaceClassSpec) DeepCopy() *WorkspaceClassSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceClassStatus) DeepCopyInto(out *WorkspaceClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceClassStatus.
func (in *WorkspaceClassStatus) DeepCopy() *WorkspaceClassStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceDeployment) DeepCopyInto(out *WorkspaceDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceDeployment.
func (in *WorkspaceDeployment) DeepCopy() *WorkspaceDeployment {
	if in == nil {
		return nil
	}
	out := new(WorkspaceDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceDeploymentList) DeepCopyInto(out *WorkspaceDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkspaceDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceDeploymentList.
func (in *WorkspaceDeploymentList) DeepCopy() *WorkspaceDeploymentList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceDeploymentSpec) DeepCopyInto(out *WorkspaceDeploymentSpec) {
	*out = *in
	out.ClusterDeploymentRef = in.ClusterDeploymentRef
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(WorkspaceResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceDeploymentSpec.
func (in *WorkspaceDeploymentSpec) DeepCopy() *WorkspaceDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceDeploymentStatus) DeepCopyInto(out *WorkspaceDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedResources != nil {
		in, out := &in.ResolvedResources, &out.ResolvedResources
		*out = new(WorkspaceResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]PrerequisiteStatus, len(*in))
		copy(*out, *in)
	}
	if in.Feasibility != nil {
		in, out := &in.Feasibility, &out.Feasibility
		*out = new(FeasibilityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]AccessEntry, len(*in))
		copy(*out, *in)
	}
	if in.FailureContext != nil {
		in, out := &in.FailureContext, &out.FailureContext
		*out = new(FailureContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceDeploymentStatus.
func (in *WorkspaceDeploymentStatus) DeepCopy() *WorkspaceDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceResourceSpec) DeepCopyInto(out *WorkspaceResourceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.PerReplica.DeepCopyInto(&out.PerReplica)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceResourceSpec.
func (in *WorkspaceResourceSpec) DeepCopy() *WorkspaceResourceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceResourceSpec)
	in.DeepCopyInto(out)
	return out
}
